/**
 * Clean all generated report artifacts.
 *
 * Removes the Cucumber JSON/HTML reports, Allure results + generated report,
 * Playwright report, and failure artifacts so the next run starts from a clean
 * slate. Run before a fresh test execution:
 *
 *   npm run report:clean
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');

/** Relative paths (from repo root) that are fully regenerated by tooling. */
const TARGETS = [
  'reports/cucumber-report',
  'reports/allure-results',
  'reports/allure-report',
  'reports/playwright-report',
  'reports/artifacts',
  'reports/screenshots',
  'reports/videos',
  'reports/cucumber-report.json',
  'reports/cucumber-report.html',
];

let removed = 0;
let failed = 0;

for (const rel of TARGETS) {
  const target = path.join(root, rel);
  try {
    fs.rmSync(target, { recursive: true, force: true });
    removed += 1;
    console.log(`[clean-reports] removed ${rel}`);
  } catch (error) {
    failed += 1;
    console.error(`[clean-reports] failed to remove ${rel}: ${error.message}`);
  }
}

console.log(`[clean-reports] done. removed=${removed} failed=${failed}`);

if (failed > 0) {
  process.exitCode = 1;
}
